### ISSUE TITLE
Help command shouldn't need configuration files

### ISSUE THREAD

**Issue by fhubik** [rhosqeauto/InfraRed#198]
$ cd InfraRed
$ cd ..
$ ir-provisioner --help
WARNING Configuration file not found, using InfraRed project dir
ERROR   Settings directory doesn't exist: settings

Is this really necesarry? I think help should be provided even without proper config files set up.

**Comment by obaranov** [comment]
The problem here is because you are changing working directory ($ cd ..) 
Actually you don't need a configuration file. We have default configuration. In that default configuration we have settings folder defined as 'settings' relative path. So the first thing after start IR will look for the 'settings' folder for the supported spec's.    In your case you don't have the 'settings' folder in the '..' folder. So we don't know how to generate settings.  That's why we are showing that error message (ERROR Settings directory doesn't exist: settings)

**Comment by fhubik** [comment]
Ah, now I get it. I doesn't make sense to print help, if the help output is generated from $whatever/settings directory. I thought there will be at least some basic usage when issuing "--help" on unconfigured IR as documentation may not be always accurate and/or updated.
